schema_version = "1.0.0"

id = "SB_path_actions"
version = "2.5.1"
name = "Path Actions"
tagline = "Open blend folder in OS explorer, and more"
maintainer = "Samuel Bernou <bernou.samuel@gmail.com>"
type = "add-on"

# Open folders, copy blender paths to clipboard

license = ["SPDX:GPL-3.0-or-later"]

website = "https://github.com/Pullusb/SB_path_actions"
tags = ["System", "Development"]

blender_version_min = "4.2.0"

copyright = ["2017-2025 Samuel Bernou"]

[permissions]
files = "Open folders, List Blend files"
clipboard = "Copy path to files"
